---
- name: update web servers
  hosts: all
  become: yes
  
  tasks:
  - name: ensure dapache is installed
    package:
      name: httpd
      state: present

  - name: ensure git is installed
    package:
      name: git
      state: present
          
  - name: ensure code is updated
    git:
      repo: 'https://github.com/ravi2krishna/ecomm.git'
      dest: /var/www/html
          
  - name: ensure SELinux is permissive
    selinux:
      policy: targeted
      state: permissive

  - name: ensure dapache is enabled
    service:
      name: httpd
      enabled: yes

  - name: ensure apache is started
    service:
      name: httpd
      state: started


...
